import { subDays } from "date-fns"

// Mock data for leads
export const mockLeads = [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    phone: "(555) 123-4567",
    companyName: "Acme Inc",
    leadStatus: "New",
    leadSource: "Website",
    createdAt: subDays(new Date(), 2).toISOString(),
    exclusivity: false,
  },
  {
    id: 2,
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    phone: "(555) 987-6543",
    companyName: "XYZ Corp",
    leadStatus: "Qualified",
    leadSource: "Referral",
    createdAt: subDays(new Date(), 3).toISOString(),
    exclusivity: true,
  },
  {
    id: 3,
    firstName: "Michael",
    lastName: "Johnson",
    email: "michael.johnson@example.com",
    phone: "(555) 456-7890",
    companyName: "Johnson LLC",
    leadStatus: "Contacted",
    leadSource: "LinkedIn",
    createdAt: subDays(new Date(), 5).toISOString(),
    exclusivity: false,
  },
  {
    id: 4,
    firstName: "Emily",
    lastName: "Williams",
    email: "emily.williams@exclusivity.com",
    phone: "(555) 234-5678",
    companyName: "Williams Co",
    leadStatus: "New",
    leadSource: "Google Ads",
    createdAt: subDays(new Date(), 1).toISOString(),
    exclusivity: true,
  },
  {
    id: 5,
    firstName: "David",
    lastName: "Brown",
    email: "david.brown@example.com",
    phone: "(555) 876-5432",
    companyName: "Brown Industries",
    leadStatus: "DNC",
    leadSource: "Facebook",
    createdAt: subDays(new Date(), 7).toISOString(),
    exclusivity: false,
  },
]

// Mock data for upload batches
export const mockUploadBatches = [
  {
    id: 1,
    fileName: "leads_batch_1.csv",
    fileType: "csv",
    status: "Completed",
    totalLeads: 150,
    cleanedLeads: 130,
    duplicateLeads: 15,
    dncMatches: 5,
    sourceName: "Website Form",
    createdAt: subDays(new Date(), 1).toISOString(),
    completedAt: subDays(new Date(), 1).toISOString(),
  },
  {
    id: 2,
    fileName: "leads_batch_2.xlsx",
    fileType: "xlsx",
    status: "Processing",
    totalLeads: 200,
    cleanedLeads: 0,
    duplicateLeads: 0,
    dncMatches: 0,
    sourceName: "Trade Show",
    createdAt: new Date().toISOString(),
    completedAt: null,
  },
  {
    id: 3,
    fileName: "leads_batch_3.csv",
    fileType: "csv",
    status: "Failed",
    totalLeads: 0,
    cleanedLeads: 0,
    duplicateLeads: 0,
    dncMatches: 0,
    sourceName: "Email Campaign",
    createdAt: subDays(new Date(), 3).toISOString(),
    completedAt: null,
  },
  {
    id: 4,
    fileName: "leads_batch_4.json",
    fileType: "json",
    status: "Completed",
    totalLeads: 75,
    cleanedLeads: 70,
    duplicateLeads: 3,
    dncMatches: 2,
    sourceName: "Partner API",
    createdAt: subDays(new Date(), 5).toISOString(),
    completedAt: subDays(new Date(), 5).toISOString(),
  },
]

// Mock data for DNC lists
export const mockDncLists = [
  {
    id: 1,
    name: "Internal DNC",
    type: "internal",
    description: "Company-wide do not contact list",
    isActive: true,
    createdAt: subDays(new Date(), 30).toISOString(),
    lastUpdated: subDays(new Date(), 2).toISOString(),
  },
  {
    id: 2,
    name: "Federal DNC",
    type: "federal",
    description: "Federal do not call registry",
    isActive: true,
    createdAt: subDays(new Date(), 60).toISOString(),
    lastUpdated: subDays(new Date(), 15).toISOString(),
  },
  {
    id: 3,
    name: "Client A DNC",
    type: "client",
    description: "Client-specific do not contact list",
    isActive: true,
    createdAt: subDays(new Date(), 45).toISOString(),
    lastUpdated: subDays(new Date(), 10).toISOString(),
  },
]

// Mock data for DNC entries
export const mockDncEntries = [
  {
    id: 1,
    value: "donotcontact@example.com",
    valueType: "email",
    source: "Manual Entry",
    reason: "Customer Request",
    dncListId: 1,
    createdAt: subDays(new Date(), 20).toISOString(),
    expiryDate: null,
  },
  {
    id: 2,
    value: "(555) 999-9999",
    valueType: "phone",
    source: "Federal Registry",
    reason: "Federal DNC",
    dncListId: 2,
    createdAt: subDays(new Date(), 40).toISOString(),
    expiryDate: null,
  },
  {
    id: 3,
    value: "opt-out@client.com",
    valueType: "email",
    source: "Client Request",
    reason: "Unsubscribed",
    dncListId: 3,
    createdAt: subDays(new Date(), 15).toISOString(),
    expiryDate: null,
  },
]

// Mock data for clients
export const mockClients = [
  {
    id: 1,
    name: "Acme Corporation",
    email: "leads@acme.com",
    phone: "(555) 123-4567",
    contactPerson: "John Manager",
    deliveryFormat: "CSV",
    deliverySchedule: "Daily",
    percentAllocation: 30,
    fixedAllocation: null,
    isActive: true,
    createdAt: subDays(new Date(), 90).toISOString(),
  },
  {
    id: 2,
    name: "XYZ Industries",
    email: "leads@xyz.com",
    phone: "(555) 987-6543",
    contactPerson: "Jane Director",
    deliveryFormat: "JSON",
    deliverySchedule: "Weekly",
    percentAllocation: 50,
    fixedAllocation: null,
    isActive: true,
    createdAt: subDays(new Date(), 60).toISOString(),
  },
  {
    id: 3,
    name: "123 Enterprises",
    email: "leads@123ent.com",
    phone: "(555) 456-7890",
    contactPerson: "Bob Executive",
    deliveryFormat: "API",
    deliverySchedule: "Real-time",
    percentAllocation: null,
    fixedAllocation: 100,
    isActive: false,
    createdAt: subDays(new Date(), 120).toISOString(),
  },
]

// Mock data for suppliers
export const mockSuppliers = [
  {
    id: 1,
    name: "Lead Gen Pro",
    email: "contact@leadgenpro.com",
    contactperson: "Sarah Sales",
    apikey: "lgp_api_12345",
    status: "Active",
    leadcost: "2.50",
    createdat: subDays(new Date(), 180).toISOString(),
  },
  {
    id: 2,
    name: "Data Partners Inc",
    email: "info@datapartners.com",
    contactperson: "Mike Marketing",
    apikey: "dpi_api_67890",
    status: "Active",
    leadcost: "3.00",
    createdat: subDays(new Date(), 150).toISOString(),
  },
  {
    id: 3,
    name: "LeadSource Direct",
    email: "support@leadsource.com",
    contactperson: "Lisa Leads",
    apikey: "lsd_api_54321",
    status: "Inactive",
    leadcost: "1.75",
    createdat: subDays(new Date(), 200).toISOString(),
  },
]

// Mock data for ROI metrics
export const mockRoiMetrics = {
  totalLeads: 1250,
  totalCost: 3125.0,
  totalRevenue: 18750.0,
  netProfit: 15625.0,
  roi: 500, // percentage
  conversionRate: 15, // percentage
  costPerLead: 2.5,
  revenuePerLead: 15.0,
  topSuppliers: [
    { name: "Lead Gen Pro", leads: 500, revenue: 8500, roi: 650 },
    { name: "Data Partners Inc", leads: 350, revenue: 5250, roi: 450 },
    { name: "LeadSource Direct", leads: 400, revenue: 5000, roi: 400 },
  ],
  bottomSuppliers: [
    { name: "Budget Leads Co", leads: 150, revenue: 1500, roi: 150 },
    { name: "Discount Data", leads: 100, revenue: 900, roi: 80 },
    { name: "Cheap Contacts", leads: 50, revenue: 400, roi: 60 },
  ],
  monthlyTrend: [
    { month: "Jan", leads: 100, revenue: 1500, cost: 250 },
    { month: "Feb", leads: 120, revenue: 1800, cost: 300 },
    { month: "Mar", leads: 150, revenue: 2250, cost: 375 },
    { month: "Apr", leads: 200, revenue: 3000, cost: 500 },
    { month: "May", leads: 180, revenue: 2700, cost: 450 },
    { month: "Jun", leads: 250, revenue: 3750, cost: 625 },
  ],
}

// Mock data for users
export const mockUsers = [
  {
    id: 1,
    username: "admin@example.com",
    fullName: "Admin User",
    email: "admin@example.com",
    role: "admin",
    createdAt: subDays(new Date(), 365).toISOString(),
  },
  {
    id: 2,
    username: "manager@example.com",
    fullName: "Manager User",
    email: "manager@example.com",
    role: "manager",
    createdAt: subDays(new Date(), 180).toISOString(),
  },
  {
    id: 3,
    username: "viewer@example.com",
    fullName: "Viewer User",
    email: "viewer@example.com",
    role: "viewer",
    createdAt: subDays(new Date(), 90).toISOString(),
  },
]

// Mock data for lead distribution
export const mockLeadDistributions = [
  {
    id: 1,
    batchId: 1,
    clientId: 1,
    leadsAllocated: 45,
    deliveryStatus: "Delivered",
    deliveryDate: subDays(new Date(), 1).toISOString(),
  },
  {
    id: 2,
    batchId: 1,
    clientId: 2,
    leadsAllocated: 75,
    deliveryStatus: "Delivered",
    deliveryDate: subDays(new Date(), 1).toISOString(),
  },
  {
    id: 3,
    batchId: 1,
    clientId: 3,
    leadsAllocated: 10,
    deliveryStatus: "Failed",
    deliveryDate: null,
  },
  {
    id: 4,
    batchId: 4,
    clientId: 1,
    leadsAllocated: 21,
    deliveryStatus: "Delivered",
    deliveryDate: subDays(new Date(), 5).toISOString(),
  },
  {
    id: 5,
    batchId: 4,
    clientId: 2,
    leadsAllocated: 35,
    deliveryStatus: "Delivered",
    deliveryDate: subDays(new Date(), 5).toISOString(),
  },
  {
    id: 6,
    batchId: 4,
    clientId: 3,
    leadsAllocated: 14,
    deliveryStatus: "Delivered",
    deliveryDate: subDays(new Date(), 5).toISOString(),
  },
]
